### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email" : "josh4@gmail.com",
    "password": "asssssdd"
}

### signin as a existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email" : "josh4@gmail.com",
    "password": "asssssdd"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a giver ID
GET http://localhost:3000/auth/3

### Find all users with a given email
GET http://localhost:3000/auth?email=josh@gmail.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email" : "aaaa@aaa.com"
}